on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
    - name: wait
      uses: m3y/random-wait-action@v0.1
      with:
        max-wait-time: 30
