on: [push]

jobs:
  bump:
    runs-on: ubuntu-latest
    steps:
    - name: Bump
      uses: anothrNick/github-tag-action@1.22.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        WITH_V: true
