on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:
    inputs: None

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
    - name: data
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
        REPOSITORY: ${{ github.repository }}
      run: |
        echo "${GITHUB_EVENT}"
        echo "${REPOSITORY_NAME}"
