on: [push]

jobs:
  tagging:
    runs-on: ubuntu-latest
    steps:
    - name: Tag
      uses: richardsimko/update-tag@master
      with:
        tag_name: testtag
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
