on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'run mode'
        required: true
        default: 'manual'

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
    - name: data
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
        REPOSITORY: ${{ github.repository }}
      run: |
        echo "${GITHUB_EVENT}"
        echo "${REPOSITORY_NAME}"
