on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    - mode:
        description: 'run mode'
        required: true
        default: 'manual'

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
    - name: data
      env:
        GITHUB_EVENT: ${{ github.event }}
      run: |
        echo ${GITHUB_EVENT}
