on:
  push:
  workflow_dispatch:
    inputs:
      mode:
        description: 'run mode'
        required: true
        default: 'manual'

jobs:
  example:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: example
      uses: m3y/rust-just-action@v1
      with:
        command: usage
        file: tmp/justfile

  print_date:
    runs-on: ubuntu-latest
    steps:
    - name: data
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
        REPOSITORY: ${{ github.repository }}
      run: |
        echo "${GITHUB_EVENT}"
        echo "${REPOSITORY}"
