on: [push]

jobs:
  label-validator:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      uses: actions/checkout@v2
      with:
        repository: m3y/.github
        token: ${{ secrets.MY_PAT }}
        path: 'templates'
    - name: check
      run: |
        if [ ! -d .github ]; then
          mkdir .github/
        fi
        if [ ! -d .github/workflows ]; then
          mkdir .github/workflows/
        fi
        cp templates/*.yaml .github/workflows/
        rm -rf templates
        ls -al
