on: [push]

jobs:
  label-validator:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - uses: actions/checkout@v2
    - name: Hello world action step
      uses: actions/checkout@v2
      with:
        repository: m3y/.github
        token: ${{ secrets.MY_PAT }}
        path: 'templates'
    - name: check
      run: |
        if [ ! -d .github ]; then
          mkdir .github/
        fi
        if [ ! -d .github/workflows ]; then
          mkdir .github/workflows/
        fi
        cp -f templates/workflow-templates/*.yml .github/workflows/
        rm -rf templates
        ls -al
        ls -al .github/workflows
    - name: update
      if: ${{ success() }}
      uses: EndBug/add-and-commit@v4
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        add: '.github/workflows'
        message: 'update workflows'
    - name: check2
      run: |
        ls .github/workflows
        git status
        git log
    - name: publish
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.MY_PAT }}
