on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:
    inputs:
      mode:
        description: 'run mode'
        required: true
        default: 'manual'

jobs:
  print_date:
    runs-on: ubuntu-latest
    steps:
    - name: data
      env:
        GITHUB_EVENT: ${{ toJson(github.event) }}
        REPOSITORY_NAME: ${{ github.event.repository.name }}
        OWNER: ${{ github.event.repository.owner.login }}
        E: ${{ toJson(env) }}
      run: |
        echo "${GITHUB_EVENT}"
        echo "${REPOSITORY_NAME}"
        echo "${OWNER}"
        echo ${{ github.repository }}
        echo ${{ github.repository_owner }}
        echo ${E}
