on: [push]

jobs:
  label-validator:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Hello world action step
      uses: actions/checkout@v2
      with:
        repository: m3y/.github
        token: ${{ secrets.MY_PAT }}
        path: 'templates'
    - name: check
      run: ls -al
